<?php
defined('MOODLE_INTERNAL') || die();

$string['pluginname']         = 'AI test generator';
$string['generate_menu']      = 'Generate an AI test';

// Capability
$string['aiquizgen:generate'] = 'Generate an AI test from a lesson or a PDF';

// Privacy
$string['privacy:metadata']   = 'The local_aiquizgen plugin does not store personal data directly. Sources provided by the teacher (Moodle lesson, PDF) are forwarded to the LLM through local_aifeedback.';

// -----------------------------------------------------------
//  Generation form
// -----------------------------------------------------------
$string['form_intro']       = 'Pick a content source and the number of questions you want generated. The LLM will produce the questions, they will be saved in a new question bank category for this course, and added to a ready-to-use quiz.';

$string['source_heading']   = 'Source';
$string['source_pdf']       = 'PDF document';
$string['source_pdf_help']  = 'PDF the LLM will mine for question material (course chapter, handout, lecture notes, etc.). A single file for now.';

$string['counts_heading']   = 'Types and counts';
$string['mcqcount']         = 'Standard Moodle multiple choice';
$string['mcqcount_help']    = 'Number of multiple-choice questions (standard Moodle qtype) to generate from the source. Between 1 and 50. Other types (AI short answer, AI essay, random-pool MCQ) will be added in upcoming development steps.';

$string['dest_heading']     = 'Destination';
$string['quizname']         = 'Title of the quiz to create';
$string['quizname_help']    = 'The quiz will be created in the general section of the course with this title. You can move and adjust it afterwards.';

$string['generate_button']  = 'Generate the test';

// Validation errors
$string['error_mcqcount_min']    = 'At least 1 question is required.';
$string['error_mcqcount_max']    = 'Maximum 50 questions per generation.';
$string['error_source_required'] = 'You must provide a source PDF file.';

// -----------------------------------------------------------
//  Status page
// -----------------------------------------------------------
$string['status_pagetitle']      = 'Generation status';

$string['status_pending']        = 'Pending';
$string['status_running']        = 'Running';
$string['status_done']           = 'Done';
$string['status_failed']         = 'Failed';

$string['status_pending_help']   = 'The job is queued. Generation will start at the next cron run.';
$string['status_running_help']   = 'The LLM is processing your request. This page refreshes automatically every 5 seconds.';
$string['status_done_help']      = 'The test was generated successfully. You can now open the quiz or the created category and adjust.';
$string['status_failed_help']    = 'Generation failed.';
$string['status_lasterror']      = 'Last error:';

$string['status_label_status']   = 'Status';
$string['status_label_created']  = 'Created at';
$string['status_label_attempts'] = 'Attempts';

$string['open_quiz']             = 'Open the quiz';
$string['open_category']         = 'Open the question category';
$string['back_to_form']          = '← Back to the generation form';

// -----------------------------------------------------------
//  Pipeline errors (handler)
// -----------------------------------------------------------
$string['source_missing']        = 'The source PDF associated with this job cannot be found in Moodle storage.';
$string['source_empty']          = 'No text could be extracted from the source PDF. The document is likely scanned/image-only, without a text layer.';
$string['llm_no_questions']      = 'The LLM did not return any usable question.';
$string['quiz_creation_failed']  = 'Quiz module creation failed.';
$string['untitled_question']     = 'Untitled question';

// -----------------------------------------------------------
//  Created metadata
// -----------------------------------------------------------
$string['category_info']         = 'Category automatically generated by the local_aiquizgen plugin.';
$string['quiz_intro_generated']  = 'Quiz automatically generated by AI. Review and adjust before publishing.';

// -----------------------------------------------------------
//  Log (display on the status page)
// -----------------------------------------------------------
$string['status_label_log']      = 'Generation log';
